apiVersion: v1
kind: Pod
metadata:
  name: mosquitto-client
spec:
  containers:
    - name: mosquitto
      image: eclipse-mosquitto:latest
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
