env:
  KEYSTORE_PASSWORD: generated
  SASL_USERNAME: generated
  SASL_PASSWORD: generated
  TRUSTSTORE_PASSWORD: hellohello

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7114
      name: http
    - port: 7143
      name: https
    - port: 7183
      name: mqtt
    - port: 7883
      name: mqtts
